# -*- coding: utf-8 -*-
{
    'name': 'Quan ly Chef',
    'version': '0.1',
    'author': 'Entrust',
    'category': 'Application',
    'license': 'AGPL-3',
    'sequence': '1',
    'summary': 'Quan ly Chef',
    'description': """Mo ta quan ly Chef""",
    'website': 'http://www.domain.com',
    'depend': ['base'],
    'data': ['views/chef.xml',
             'views/menu.xml',
             ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
}
